config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  get '/about' => 'pages#about'
  get '/blog'=> 'pages#blog'
  root 'pages#home'
  

end

app/models/contact.rb
class Contact < ActiveRecord::Base

	validates :name, :email, presence: true

	# Add e-mail validation 

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def index
	end

	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(contact_params)

		if @contact.save
			flash[:success] = "Message sent successfully."
			redirect_to new_contact_path
		else
			flash[:danger] = @contact.errors.messages
			redirect_to new_contact_path
		end		
	end

	private
	def contact_params
		params.require(:contact).permit(:name, :email, :comments)
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end

	def about		
	end

	def blog
	end
	
end

app/views/contacts/index.html.erb
<% content_for :title do %>Contact<% end %>
<div class="contacts-welcome text-center">
	<h1>Contact</h1>
</div>
<div class="content">
	<div class="row">
		<p>For more information please fill out the following.</p>
	</div>
</div>

app/views/contacts/new.html.erb
<% content_for :title do %>Contact<% end %>
<div class="welcome text-center row">
	<div class="welcome-text-area col-md-offset-3 col-md-6">
		<h1>Contact</h1>
	</div>
</div>
<div class="content">
	<div class="row">
			<% flash.each do | key , value | %>
	        	<%= content_tag :div, value, class: "alert alert-#{key} col-md-12" %>
	      	<% end %>
	</div>
	<div class="row">
		      	
	      	<div class="col-md-7">
	      		<p>Please provide your name, email, and a brief comment if you would like to recieve a quote on services. Allow up to 48 hours for a response.</p>

	      	</div>
			<div class="col-md-5 well">
				<%= form_for @contact do |f| %>
					<div class="form-group">
					<%= f.label :name %>
					<%= f.text_field :name, class: "form-control" %>
					</div>

					<div class="form-group">	
					<%= f.label :email %>
					<%= f.email_field :email, class: "form-control" %>
					</div>

					<div class="form-group">
					<%= f.label :comments %>
					<%= f.text_area :comments, class: "form-control" %>
					</div>

					<%= f.submit 'Submit', class: 'btn btn-default pull-right' %>
				<% end %>
			</div>
			
	</div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="container">
		<p class="text-muted">2015 Roberson Analytics</p>
	</div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
        <span class="sr-only">Toggle navigation</span> 
        <!-- these three spans below create the three bars in the navigation button when in smaller displays -->
        <span class="icon-bar"></span> 
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

        <%= link_to root_path, class: 'navbar-brand' do %>
          Roberson Analytics
        <% end %>
        
    </div>
    <div class="collapse navbar-collapse" id="main-nav-collapse">
        <%= render 'layouts/navigation_links' %>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<ul class="nav navbar-nav navbar-right text-uppercase">
	<li><%= link_to 'About', about_path %></li>
	<li><%= link_to 'Blog', blog_path %></li>
	<li><%= link_to 'Contact', new_contact_path %><li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Roberson Analytics" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Learn Rails" %>">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <article>
      <%= yield %>
    </article>
    
      <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<div class="welcome text-center row">
	<div class="welcome-text-area col-md-offset-3 col-md-6">
		<h1>About</h1>
	</div>
</div>
<div class="content">
	<div class="row">
		<h3 class="text-uppercase">Joshua Roberson <small>Owner</small></h3>
		<p>A versatile data scientist with over five years experience in a variety of industries including banking, investments, real estate, and academic research. I love working with data and providing insightful analytics to allow management to make better business decisions.</p>
		<p>Some of the areas I specialize in include:</p>
		<br>
		<div>
		<div class="col-md-4">
			<div class="panel panel-default">
  				<div class="panel-heading text-center">
    				<h3 class="panel-title"><i class="fa fa-database" aria-hidden="true"></i>  Database</h3>
  				</div>
				<div class="panel-body text-left">
					<ul class="list-unstyled">
						<li>Database design and maintenance</li>
						<li>Data integration into relational models</li>
						<li>Generate reports and views</li>
				   	</ul>
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="panel panel-default">
  				<div class="panel-heading text-center">
    				<h3 class="panel-title"><i class="fa fa-bar-chart" aria-hidden="true"></i>  Analysis</h3>
  				</div>
				<div class="panel-body text-left">
					<ul class="list-unstyled">
						<li>Design automated data pipelines</li>
						<li>Statistical methods and analysis</li>
						<li>Data visualization</li>
				   	</ul>				   
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="panel panel-default">
  				<div class="panel-heading text-center">
    				<h3 class="panel-title"><i class="fa fa-desktop" aria-hidden="true"></i>  Web Development</h3>
  				</div>
				<div class="panel-body">
					<ul class="list-unstyled">
						<li>Full stack web development</li>
						<li>Database services for web features</li>
						<li>Responsive web design</li>
						<li>Social media integration</li>
						<li>Google Analytics analysis</li>												
				   	</ul>
				</div>
			</div>
		</div>
		</div>
<!-- 		<ul>
			<li>Database design and maintenance.</li>
			<li>Data analysis pipelines.</li>
			<li>Report and web application data products.</li>
			<li>Utilized</li>
		</ul> -->
	</div>
</div>

app/views/pages/blog.html.erb
<div class="welcome text-center row">
	<div class="welcome-text-area col-md-offset-3 col-md-6">
		<h1>Blog</h1>
	</div>
</div>	
<div class="content">
	<div class="row">
		<p>The blog is still in development! Check back often for updates. In time I hope to add a unique assortment of software development tips, tricks, and use cases.</p>
	</div>		
</div>

app/views/pages/home.html.erb
<div class="welcome text-center row">
	<div class="welcome-text-area col-md-offset-3 col-md-6">
		<h1>Welcome</h1>
	</div>
</div>
<div class="content">
	<div class="row">
		<p>Roberson Analytics is owned and operated by Joshua Roberson. As an independent freelancer with over nine years of data analysis and web development experience I can provide my clients with reliable and personalized experience. I am based out of College Station, Texas right in the heart of Aggieland.</p>
		<p>I put a tremendous amount of pride and effort into every client's needs from start to finish. My work is efficient and competively priced.</p>
		<p>Check out the about tab to see my full line of services.</p>
	</div>
</div>